serenity.project.name=Serenity and Cucumber Quick Start

#Appium
#webdriver.driver=appium
#appium.hub=http://127.0.0.1:4723
#appium.platformName=Android
#appium.deviceName=Medium Phone API 36.1

webdriver.driver= appium
#webdriver.timeouts.implicitlywait = 50000
#webdriver.wait.for.timeout = 100000

appium.hub = http://localhost:4723/

####### Android CAPS ######
appium.automationName=UiAutomator2
appium.platformName = Android
appium.platformVersion = 11.0
appium.deviceName  = Pixel 9a
appium.app= F:\\Documentos\\POC\\appium\\arquetipo-serenitybb-librerias-actualizadas\\src\\test\\resources\\apks\\ApiDemos-debug.apk
appium.newCommandTimeout = 2000

